// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/onboarding": {
    params: {};
  };
  "/dashboard": {
    params: {};
  };
  "/settings": {
    params: {};
  };
  "/settings/alerts": {
    params: {};
  };
  "/settings/keys": {
    params: {};
  };
  "/settings/sources": {
    params: {};
  };
  "/settings/team": {
    params: {};
  };
  "/settings/workspace": {
    params: {};
  };
  "/streams": {
    params: {};
  };
  "/streams/:streamId": {
    params: {
      "streamId": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/login" | "/onboarding" | "/dashboard" | "/settings" | "/settings/alerts" | "/settings/keys" | "/settings/sources" | "/settings/team" | "/settings/workspace" | "/streams" | "/streams/:streamId";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/login.tsx": {
    id: "routes/login";
    page: "/login";
  };
  "routes/onboarding.tsx": {
    id: "routes/onboarding";
    page: "/onboarding";
  };
  "routes/_layout.tsx": {
    id: "routes/_layout";
    page: "/dashboard" | "/settings" | "/settings/alerts" | "/settings/keys" | "/settings/sources" | "/settings/team" | "/settings/workspace" | "/streams" | "/streams/:streamId";
  };
  "routes/_layout.dashboard.tsx": {
    id: "routes/_layout.dashboard";
    page: "/dashboard";
  };
  "routes/_layout.settings.tsx": {
    id: "routes/_layout.settings";
    page: "/settings" | "/settings/alerts" | "/settings/keys" | "/settings/sources" | "/settings/team" | "/settings/workspace";
  };
  "routes/_layout.settings._index.tsx": {
    id: "routes/_layout.settings._index";
    page: "/settings";
  };
  "routes/_layout.settings.alerts.tsx": {
    id: "routes/_layout.settings.alerts";
    page: "/settings/alerts";
  };
  "routes/_layout.settings.keys.tsx": {
    id: "routes/_layout.settings.keys";
    page: "/settings/keys";
  };
  "routes/_layout.settings.sources.tsx": {
    id: "routes/_layout.settings.sources";
    page: "/settings/sources";
  };
  "routes/_layout.settings.team.tsx": {
    id: "routes/_layout.settings.team";
    page: "/settings/team";
  };
  "routes/_layout.settings.workspace.tsx": {
    id: "routes/_layout.settings.workspace";
    page: "/settings/workspace";
  };
  "routes/_layout.streams._index.tsx": {
    id: "routes/_layout.streams._index";
    page: "/streams";
  };
  "routes/_layout.streams.$streamId.tsx": {
    id: "routes/_layout.streams.$streamId";
    page: "/streams/:streamId";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/_index": typeof import("./app/routes/_index.tsx");
  "routes/login": typeof import("./app/routes/login.tsx");
  "routes/onboarding": typeof import("./app/routes/onboarding.tsx");
  "routes/_layout": typeof import("./app/routes/_layout.tsx");
  "routes/_layout.dashboard": typeof import("./app/routes/_layout.dashboard.tsx");
  "routes/_layout.settings": typeof import("./app/routes/_layout.settings.tsx");
  "routes/_layout.settings._index": typeof import("./app/routes/_layout.settings._index.tsx");
  "routes/_layout.settings.alerts": typeof import("./app/routes/_layout.settings.alerts.tsx");
  "routes/_layout.settings.keys": typeof import("./app/routes/_layout.settings.keys.tsx");
  "routes/_layout.settings.sources": typeof import("./app/routes/_layout.settings.sources.tsx");
  "routes/_layout.settings.team": typeof import("./app/routes/_layout.settings.team.tsx");
  "routes/_layout.settings.workspace": typeof import("./app/routes/_layout.settings.workspace.tsx");
  "routes/_layout.streams._index": typeof import("./app/routes/_layout.streams._index.tsx");
  "routes/_layout.streams.$streamId": typeof import("./app/routes/_layout.streams.$streamId.tsx");
};